version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: ontime-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - ontime-mongo-network
    volumes:
      - ./mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    container_name: ontime-mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
    networks:
      - ontime-mongo-network

networks:
  ontime-mongo-network:
    driver: bridge
